In [10]:
# AUC
def cal_auc(score_list):
    score_list = sorted(score_list, key=lambda x: x[0], reverse=True)
    #(totalPosRank - (nump+1)nump/2)/(nump*numn)
    pos_cnt = 0
    neg_cnt = 0
    total_pos_rank = 0
    for i in range(len(score_list)):
        rank = i + 1
        if score_list[i][1] == 1:
            total_pos_rank += rank
            pos_cnt += 1
        else:
            neg_cnt += 1
    print(score_list)
    return (total_pos_rank - (pos_cnt + 1) * pos_cnt / 2.0) / (pos_cnt * neg_cnt)
score_list = [[2,1],[1,0],[6,1],[4,0],[5,0],[3,1]]
auc = cal_auc(score_list)
print("auc={}".format(auc))

[[6, 1], [5, 0], [4, 0], [3, 1], [2, 1], [1, 0]]
auc=0.4444444444444444


In [23]:
# L1 & L2
import numpy as np
def l1_norm(x, epsilon=1e-10):
    output = x / np.maximum(np.sum(np.abs(x)), epsilon)
    return output

def l2_norm(x, axis=-1, epsilon=1e-10):
    output = x / np.sqrt(np.maximum(np.sum(np.square(x), axis=axis, keepdims=True), epsilon))
    return output
x = np.array([[1,2,3,4],[1,2,3,4]])
#x = np.arange(12).reshape([1,3,4])
print(x)
print(l1_norm(x))
print(l2_norm(x))

[[1 2 3 4]
 [1 2 3 4]]
[[0.05 0.1  0.15 0.2 ]
 [0.05 0.1  0.15 0.2 ]]
[[0.18257419 0.36514837 0.54772256 0.73029674]
 [0.18257419 0.36514837 0.54772256 0.73029674]]


In [34]:
# dropout
import numpy as np
def dropout(x, p, mode='train'):
    keep_prob = 1 - p
    if mode == 'train':
        x *= np.random.binomial(1, keep_prob, size=x.shape) / keep_prob
    return x

x = np.array([[.1,.2,.3,.4,],[.6,.7,.8,.9]])
print(dropout(x, 0.5, 'train'))
x = np.array([[.1,.2,.3,.4,],[.6,.7,.8,.9]])
print(dropout(x, 0.5, 'predict'))

[[0.2 0.4 0.6 0. ]
 [0.  0.  1.6 0. ]]
[[0.1 0.2 0.3 0.4]
 [0.6 0.7 0.8 0.9]]
